project:
  type: website

execute:
  freeze: auto

website:
  title: "AD688 O1 Fall '26 Career Evaluation Team Project - Group 5"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: introduction.qmd
        text: "Introduction"
      - href: data_preparation.qmd
        text: "Data Preparation"
      - href: market_baseline.qmd
        text: "Market Baseline"
      - href: eda.qmd
        text: "Exploratory Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "Predictive Modeling"
      - href: career_evaluation.qmd
        text: "Career Evaluation"
      - href: final_recommendations.qmd
        text: "Final Recommendations"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib